### ISSUE TITLE
Problem with Linux64 Build

### ISSUE THREAD

**Issue by tkulpa** [Vocaluxe/Vocaluxe#271]
```
Build FAILED.

Warnings:

/home/szope/Projects/Vocaluxe/Vocaluxe.sln:  warning : Ignoring vcproj 'PitchTracker'.
/home/szope/Projects/Vocaluxe/Vocaluxe.sln:  warning : Failed to find project 54a48af7-515c-4edd-b395-2bffa096050a

/home/szope/Projects/Vocaluxe/Vocaluxe.sln (default targets) ->
(Build target) ->
/home/szope/Projects/Vocaluxe/VocaluxeLib/VocaluxeLib.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	Menu/SongMenu/CSongMenuList.cs(639,17): warning CS0219: The variable `totalSongNumber' is assigned but its value is never used
	Menu/SongMenu/CSongMenuFramework.cs(292,21): warning CS0219: The variable `check' is assigned but its value is never used

Errors:

/home/szope/Projects/Vocaluxe/Vocaluxe.sln (default targets) ->
(Build target) ->
/home/szope/Projects/Vocaluxe/Vocaluxe/Vocaluxe.csproj (default targets) ->
(EnsureNuGetPackageBuildImports target) ->

	/home/szope/Projects/Vocaluxe/Vocaluxe/Vocaluxe.csproj: error : This project references NuGet package(s) that are missing on this computer. Rebuild for automatic package restore. The missing file is ../packages/vocaluxe.dependencies.aforgevideo.1.0.1/build/vocaluxe.dependencies.aforgevideo.targets.

/home/szope/Projects/Vocaluxe/Vocaluxe.sln (default targets) ->
(Build target) ->
/home/szope/Projects/Vocaluxe/Vocaluxe/Vocaluxe.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (_RecordCleanFile target) ->

	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Could not find a part of the path "/home/szope/Projects/Vocaluxe/Vocaluxe/obj/x64/ReleaseLinux/Vocaluxe.csproj.FilesWrittenAbsolute.txt".  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x001cf] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
  at System.IO.StreamWriter.CreateFile (System.String path, System.Boolean append, System.Boolean checkHost) [0x00022] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize, System.Boolean checkHost) [0x00061] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.IO.StreamWriter..ctor (System.String path, System.Boolean append) [0x00008] in <8f2c484307284b51944a1a13a14c0266>:0 
  at (wrapper remoting-invoke-with-check) System.IO.StreamWriter:.ctor (string,bool)
  at Microsoft.Build.Tasks.WriteLinesToFile.Execute () [0x00034] in <063b27d92e604f699a7eab9b5479d82b>:0 

	 4 Warning(s)
	 2 Error(s)
```

Im getting this kind of error after make

Linux S161 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by lukeIam** [comment]
Did you run `nuget.exe restore` ?

**Comment by tkulpa** [comment]
Im on linux

**Comment by lukeIam** [comment]
> Im on linux

nuget does also work on Linux (with mono) and is required to satisfy all the required dependencies.

**Comment by tkulpa** [comment]
Ok, it worked, now i have this error: 
```
Errors:

/home/szope/Projects/Vocaluxe/Vocaluxe.sln (default targets) ->
(Build target) ->
/home/szope/Projects/Vocaluxe/Vocaluxe/Vocaluxe.csproj (default targets) ->
(managedDepCopyAfterBuild target) ->

	/home/szope/Projects/Vocaluxe/Vocaluxe/Vocaluxe.csproj: error : Cannot copy /home/szope/Projects/Vocaluxe/Output/System.Data.SQLite.xml to /home/szope/Projects/Vocaluxe/Vocaluxe/@(_OutDirItem->'%(FullPath)')libs/managed/System.Data.SQLite.xml, as the source file doesn't exist.

	 8 Warning(s)
	 1 Error(s)
```

**Comment by derivator** [comment]
Building on linux is kind of painful right now... [This](https://github.com/derivator/Vocaluxe/commits/travis) is the last branch that I managed to produce a playable Vocaluxe with on Linux, but it contains some unrelated commits (that I wanted for my Vocaluxe party) and is based on the test branch for travis, so it's NOT merge ready! (I used the travis branch because I just wanted to get something running, and that had the most issues already fixed... at some point, I guess travis support and building on linux became the same project).

Anyway, that branch does contain a fix for your problem (commit 32cd934b), for some other problems that only become visible at runtime, and a workaround for an issue with xbuild.  
From the C# side, it uses (and requires) the new acinerella version, because the old one didn't compile anymore with the newest ffmpeg, but it doesn't contain the c code to build the new version, though @lukeIam [has fixed that](https://github.com/Vocaluxe/Vocaluxe/pull/248#issuecomment-268585299) in his latest newAcinerella branch. I don't know if that will compile with older ffmpeg versions/whatever Debian ships though. If you merge that code into my travis branch, you might be able to make a franken-build that works, if it works, please let me know. A proper merge-ready and playable linux build at this point would require:

* cherry-picking fixes from my (old) travis branch into @lukeIam's new travis branch
* properly merging newAcinerella (including c code for the new version)

The main possible problem that then remains is getting a compatible ffmpeg version for your distribution.
In the future, it may be worth thinking about something like [Flatpak](http://flatpak.org/#about) for distributing linux builds, but this is (I would think) not a one-day project, and I don't have the time right now...

**Comment by lukeIam** [comment]
> . I don't know if that will compile with older ffmpeg versions/whatever Debian ships though.

I got latest ffmpeg compiling on Ubuntu 12.04 (used by the travis build bots):  
https://github.com/lukeIam/Vocaluxe/tree/travis
Or with pre build ffmpeg binaries:  
https://github.com/lukeIam/Vocaluxe/tree/travis_ffmpegPrebuild_test

**Comment by lukeIam** [comment]
My next try: getting Vocaluxe starting on Ubuntu 16.04  
Building works without problems.
I also cloud fulfill most of the runtime dependencies (some with really hacky solutions):
But finally after 4 days of trying I'm stuck at getting `libgstreamersharpglue.so` (gstreamer-sharp does not build with Ubuntu 16.04 and if I patch a problem the next occurs).

**Comment by Stefan1200-de** [comment]
I now tried to make the latest nightly of Vocaluxe 0.4.0.beta1-31-g2e6b388 on Linux Mint 18.1 (which is based on Ubuntu 16.04, if I remember it correctly). Well, it stopped me here:
```sh
make -C PitchTracker
make[1]: Verzeichnis „/home/stefan/Downloads/Vocaluxe-Nightly/PitchTracker“ wird betreten
gcc -shared -o libPitchTracker.dll.so -fPIC compatibility.o dywapitchtrack/dywapitchtrack.o dywapitchtrack/ptDyWa.o FFT/FFT.o FFT/RealFFTf.o Helper.o performous/pitch.o ptAKF.o PitchWrapper.o
strip libPitchTracker.dll.so
cp libPitchTracker.dll.so ../Output/
make[1]: Verzeichnis „/home/stefan/Downloads/Vocaluxe-Nightly/PitchTracker“ wird verlassen
make -C Vocaluxe/Lib/Video/Acinerella
make[1]: Verzeichnis „/home/stefan/Downloads/Vocaluxe-Nightly/Vocaluxe/Lib/Video/Acinerella“ wird betreten
gcc -c -fPIC acinerella.c -I /usr/local/include
acinerella.c: In function ‘cpymetadata’:
acinerella.c:344:9: warning: implicit declaration of function ‘strncpy_s’ [-Wimplicit-function-declaration]
         strncpy_s(tar, len, entry->value, len);
         ^
acinerella.c: In function ‘ac_get_stream_info’:
acinerella.c:517:42: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
     switch (self->pFormatCtx->streams[nb]->codecpar->codec_type) {
                                          ^
acinerella.c:524:46: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
                 self->pFormatCtx->streams[nb]->codecpar->width;
                                              ^
acinerella.c:526:46: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
                 self->pFormatCtx->streams[nb]->codecpar->height;
                                              ^
acinerella.c:529:46: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
                 self->pFormatCtx->streams[nb]->codecpar->sample_aspect_ratio.num;
                                              ^
acinerella.c:531:46: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
                 self->pFormatCtx->streams[nb]->codecpar->sample_aspect_ratio.den;
                                              ^
acinerella.c:551:46: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
                 self->pFormatCtx->streams[nb]->codecpar->sample_rate;
                                              ^
acinerella.c:553:46: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
                 self->pFormatCtx->streams[nb]->codecpar->channels;
                                              ^
acinerella.c:556:50: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
             switch (self->pFormatCtx->streams[nb]->codecpar->format) {
                                                  ^
acinerella.c: In function ‘ac_create_video_decoder’:
acinerella.c:683:5: error: unknown type name ‘AVCodecParameters’
     AVCodecParameters* pCodecParam = ((lp_ac_data)(pacInstance))->pFormatCtx->streams[nb]->codecpar;
     ^
acinerella.c:683:90: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
     AVCodecParameters* pCodecParam = ((lp_ac_data)(pacInstance))->pFormatCtx->streams[nb]->codecpar;
                                                                                          ^
acinerella.c:688:47: error: request for member ‘codec_id’ in something not a structure or union
               avcodec_find_decoder(pCodecParam->codec_id))) {
                                               ^
acinerella.c:693:5: warning: implicit declaration of function ‘avcodec_parameters_to_context’ [-Wimplicit-function-declaration]
     avcodec_parameters_to_context(pDecoder->pCodecCtx, pCodecParam);
     ^
acinerella.c: In function ‘ac_create_audio_decoder’:
acinerella.c:741:5: error: unknown type name ‘AVCodecParameters’
     AVCodecParameters* pCodecParam = self->pFormatCtx->streams[nb]->codecpar;
     ^
acinerella.c:741:67: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
     AVCodecParameters* pCodecParam = self->pFormatCtx->streams[nb]->codecpar;
                                                                   ^
acinerella.c:744:60: error: request for member ‘codec_id’ in something not a structure or union
     ERR(pDecoder->pCodec = avcodec_find_decoder(pCodecParam->codec_id));
                                                            ^
acinerella.c:41:15: note: in definition of macro ‘ERR’
         if (!(E)) {     \
               ^
acinerella.c: In function ‘ac_decode_video_package’:
acinerella.c:816:8: warning: implicit declaration of function ‘avcodec_send_packet’ [-Wimplicit-function-declaration]
     if(avcodec_send_packet(pDecoder->pCodecCtx, pkt->pPack) != 0)
        ^
acinerella.c:821:9: warning: implicit declaration of function ‘avcodec_receive_frame’ [-Wimplicit-function-declaration]
     if (avcodec_receive_frame(pDecoder->pCodecCtx, pDecoder->pFrame) != 0)
         ^
makefile:2: die Regel für Ziel „acinerella“ scheiterte
make[1]: *** [acinerella] Fehler 1
make[1]: Verzeichnis „/home/stefan/Downloads/Vocaluxe-Nightly/Vocaluxe/Lib/Video/Acinerella“ wird verlassen
makefile:4: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by lukeIam** [comment]
looks like a wrong ffmpeg version is used...

**Comment by bidinou** [comment]
Hi ! Definitely looking forward to an easy way to get it to work :-) (flatpack, snap ?)
Cheers !

**Comment by lukeIam** [comment]
For flatpack, snap, ... we also need to compile all dependencies successfully and unfortunately thats the blocker at the moment.

**Comment by lukeIam** [comment]
Updated the LinuxHowTo: https://github.com/Vocaluxe/Vocaluxe/pull/376/files (currently open pr)
+
My travis branch (https://github.com/lukeIam/Vocaluxe/tree/travis) is up to date with develop and compiles successfully with Ubuntu 14.04.
We still have the runtime dependency problems but at least it compiling successfully.
